title: Chiel Kunkels
description: >
  Personal site of Chiel Kunkels, all-round developer.
url: http://kunkels.me
markdown: redcarpet
highlighter: 'rouge'
permalink: /:title/

redcarpet:
  extensions: [ 'smart' ]
